### PR TITLE
add color picker element

### PR DESCRIPTION
**Pull request by roykolak**
This element demonstrates....
- styling a shadow DOM host (:host)
- using attribute binding (style=$, class=$, ...)
- using computed properties as a decorator
- property observers
- listening for dom events (note the format: '[#ID].[event]')
- referencing cached elements by id (this.$.[ID])

### CODE REVIEW

**Comment by tomkersten** [comment]
Aside: It [looks like](https://www.polymer-project.org/1.0/docs/devguide/properties.html#configure-values) default values are supposed to be wrapped in functions (vs. the bare Array). Am I reading that correctly or was the naked Array you had coo'?

**Comment by roykolak** [comment]
Ah yeah, good catch. 

> The value may either be a primitive value, or a function that returns a value (which should be used for | initializing Objects and Arrays to avoid shared objects on instances).

..." to avoid shared objects on instances". Not totally sure what that means.. anyone?

**Comment by tomkersten** [comment]
I'm _guessing_ they mean to avoid having, say, an Array that is the same underlying Object being shared b/t two instances of an element (`color-picker`). If that were to happen, having two elements which modified that shared item would end up affecting both elements.

Yea?

**Comment by roykolak** [comment]
genius. that's totally it. :shipit:

**Comment by dkordik** [comment]
must have something to do with the fact that objects are passed by reference

**Comment by dkordik** [comment]
ah crap, didn't have your later messages. [?]

**Pull request merged**
